### PR TITLE
Add highlighting of all messages from a certain user

### PR DESCRIPTION
**Pull request by DatGuy1**

### CODE REVIEW

**Comment by fourtf** [comment]
The pattern used for this commit should not be used anymore (Creating a textbox and storing the elements joined with a newline).

Instead the pattern used for the "Highlights" settings should be used (Creating a `UserHighlight`, a `UserHighlightModel` and a `UserHighlightController` class.

Accepting the PR right now would mean that it needs to be rewritten down the line. I will also have to refactor the existing settings that don't use this pattern at some point.

**Comment by DatGuy1** [comment]
I closed this? Thanks git. Anyways, I'm going to keep working on this. Not sure what I did to close it.

**Comment by Yardanico** [comment]
@DatGuy1 it's not git, it's GitHub. Just reopen this PR from GitHub website

**Comment by DatGuy1** [comment]
Continued in #564

**Pull request closed without merging**
