### PR TITLE
Added scrolling over tabs with wheel to switch channels.

### PR DESCRIPTION
**Pull request by 23rd**
heh3

### CODE REVIEW

**Comment by pajlada** [comment]
Something with the mouse scroll multiplier or wheel step stuff makes this behave strangely on my i3 Linux setup. I have to scroll my wheel three times before it switches tab

**Comment by 23rd** [comment]
I thought that scrolling on each step of the wheel would be very sensitive for users. But if this is normal behavior for you, I will remove the "three-step" scroll.

**Comment by gempir** [comment]
Doesn't work at all on macOS

**Comment by 23rd** [comment]
Oops.

**Comment by gempir** [comment]
Woops aswell. @23rd Sorry, works perfectly fine on macOS aswell.

**Pull request merged**
