### PR TITLE
stop emotes from being cut off

### LINKED ISSUE #897: ffz emotes that are higher than wide will get cut off
Seems to be unaffected by emote size or UI scale
image

### PR DESCRIPTION
**Pull request by Ckath**
fixes #897, not entirely sure why this was ever commented out in the first place, works fine like this again though

### CODE REVIEW

**Comment by 23rd** [comment]
This PR fixes a trimming of emotes, but breaks a display of effect for (dis/re)connected messages (fc93d7b7388e65abeaa5fa915f287b90e7590a96). 
image

**Comment by Ckath** [comment]
didn't really notice it as it looks like this on mine, guess those lines weren't commented out for no reason at all 
image

**Comment by Ckath** [comment]
oh now theres even conflics, I'll look at again another time if it stays

**Comment by hemirt** [comment]
request for reopen

**Comment by Ckath** [comment]
@hemirt alright, I was going to look at it 'eventually' and just start over looking at random places that messed with scale and made the emotes cutoff

**Comment by Ckath** [comment]
think this does the trick actually, if it does pls merge so I can go back to using upstream from my aur package instead of a fork with one line changed

**Comment by Ckath** [comment]
@pajlada it would be great if this one line could be changed in the `pajlada-dev` branch too so the emote issue is fixed for the time being in the aur package

**Comment by Ckath** [comment]
merged to `pajlada-dev` in #1003 no reason to keep this open

**Pull request closed without merging**
