### PR TITLE
Initial work of rewriting match link

### PR DESCRIPTION
**Pull request by LajamerrMittesdine**
This is just some initial work on rewriting the match hyperlink feature.

### CODE REVIEW

**Comment by Yardanico** [comment]
:+1: No more highlights of things like "test.test" :joy: :lit: :100:

**Comment by fourtf** [comment]
- The TLDs resource file should be delimited by a newline instead of | so it's not an 11k long line. Also makes it less of a git fiesta.
- The TDLs should be loaded from the resource file instead of being embedded into the source file.
- No temp files should be created by the script or they should at least be deleted afterwards.
- SFTP matching should be removed.

**Comment by LajamerrMittesdine** [comment]
Did a little bit of changes.

Still working on eliminating the rest of the temp files.
Then working on changing messagebuilder.cpp so that it doesn't include the massive length of text inside of it.

**Comment by LajamerrMittesdine** [comment]
Making a newer pull request. Since this one has conflicts.

**Pull request closed without merging**
