### PR TITLE
Added build details for Linux

### PR DESCRIPTION
**Pull request by Ian321**

### CODE REVIEW

**Comment by nuuls** [comment]
🤔

**Comment by Ian321** [comment]
:thinking:

**Comment by pajlada** [comment]
@Ian321 Which distro/version are these installation instructions for? Would be nice to specify (i.e. Debian Jessie)

**Comment by Ian321** [comment]
@pajlada  [KDE neon](https://neon.kde.org/) latest version  ( it's currently based on Ubuntu 16.04.2 LTS  )

**Pull request merged**
