### PR TITLE
BTTV changed to uppercase

### PR DESCRIPTION
**Pull request by Kllrt**
I guess I have autismo or something, but this bothered me for some time, sorry.

### CODE REVIEW

**Comment by fourtf** [comment]
With this change it would say `BTTV` for global emotes, and as before `Bttv` for channel emotes and `BetterTTV in the settings.

I suggest that it would be best if it is changed to BetterTTV in all instances as that seems to be the official name on the website www.nightdev.com/betterttv

**Comment by Kllrt** [comment]
You mean also for variables and stuff or just text (which user can see)?

**Comment by fourtf** [comment]
Just text that the user can see

**Comment by Kllrt** [comment]
I guess it should be okay now? 😅

**Pull request merged**
