### PR TITLE
Fixed tooltip of twitch emotes in a cheesy fashion

### PR DESCRIPTION
**Pull request by apa420**

### CODE REVIEW

**Comment by 23rd** [comment]
I mean I'm not sure that `Twitch Emote` line is really needed.

**Comment by apa420** [comment]
There are lines for other emote types like FFZ channel emotes, FFZ Global emotes etc

**Comment by 23rd** [comment]
It makes much more sense to add a line to which channel current emote belongs.
And if emote is global add line "Global Twitch Emote".

**Comment by pajlada** [comment]
sure, this works for now until we can add a tooltip with more granularity (Global emote, sub emote etc)

**Pull request merged**
