### PR TITLE
Pubsub messages now go into the correct channel

### PR DESCRIPTION
**Pull request by apa420**
Now pr's to the right branch

### CODE REVIEW

**Comment by hemirt** [comment]
it's better to use splitRef if youre not copying Awoo

**Comment by pajlada** [comment]
@hemirt you can make a PR fixing that PogChamp

**Comment by hemirt** [comment]
@pajlada any love for #990

**Comment by pajlada** [comment]
@hemirt too big of a PR for me to want to go through right now, sorry

**Comment by hemirt** [comment]
sure, maybe later then

**Comment by FeelsDankMan** [comment]
useless comment AWOO

**Pull request merged**
