### PR TITLE
Make the 'add account' popup box go to foreground

### PR DESCRIPTION
**Pull request by DatGuy1**
Previously it just stayed behind. i only tested this in windows since I don't have any OSX/Linux vms but raise() should just work on them.

### CODE REVIEW

**Comment by pajlada** [comment]
Tested it in Linux with the i3 window manager. Compiles and runs as expected. Should be tested on Windows before merging at least

**Comment by DatGuy1** [comment]
Already tested on windows, at least with my build.

**Comment by fourtf** [comment]
Please use the USEWINSDK define instead of FMT_USE_WINDOWS_H, then I will merge it.

**Comment by DatGuy1** [comment]
Done. Also, there's probably a few other bugs like this, already found it in look->font select. when c2 is pretty much ready for public release I can go over "popup" widgets and add that

**Comment by fourtf** [comment]
You have to use `#ifdef USEWINSDK` instead of `#if USEWINSDK`

**Pull request merged**
